title: ğŸƒğŸ»â€â™€ ì¡°ë¹¡ ë¸”ë¡œê·¸ ğŸƒğŸ»â€â™‚ï¸
name: ì¡°ë¹¡ ë¸”ë¡œê·¸
description: ì±… ì½ê³  ì •ë¦¬í•´ìš”
baseurl: ""
url: "https://jo-pk.github.io"

author: Joanne and PK

exclude: ["README.md"]

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

asset_url: /assets

category_descriptions:
  self: "personal posts, or posts about social topics"
  code: "posts about programming projects or concepts"
